### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by wenzeslaus** [pketh/github-report-card#2]
Hi. This is quite useful repository as ready to use code or as an example. Thanks! Can you please add a license? I assume this is MIT or even CC0 but a clear message would be nice.

**Comment by pketh** [comment]
absolutely, I'll add the MIT right now. I'm glad you've found it useful

**Comment by pketh** [comment]
donezo https://github.com/pketh/github-report-card/blob/gh-pages/LICENSE.md
